"""
Build the Windows icon (.ico) from the master PNG.

The icon artwork (an open book before a library, with the 'A.-K.' tag) is
generated by ``tools/render_icons.py`` — a browser-based tool — into
``static/icon.png``. This step packages that committed master into a
multi-resolution ``.ico`` using Pillow only, so it also runs in CI with no
browser dependency. Re-run whenever ``static/icon.png`` changes.

Usage:
    python tools/make_icon.py
"""

from __future__ import annotations

import argparse
import logging
from pathlib import Path

from PIL import Image

logging.basicConfig(level=logging.INFO, format="%(levelname)s  %(message)s")
log = logging.getLogger("make_icon")

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_SRC = ROOT / "static" / "icon.png"
DEFAULT_ICO = ROOT / "static" / "icon.ico"

ICON_SIZES = [(16, 16), (32, 32), (48, 48), (64, 64), (128, 128), (256, 256)]


def generate(src_path: Path, ico_path: Path) -> None:
    """Package the master PNG into a multi-size .ico."""
    master = Image.open(src_path).convert("RGBA")
    ico_path.parent.mkdir(parents=True, exist_ok=True)
    master.save(ico_path, format="ICO", sizes=ICON_SIZES)
    log.info(
        "Wrote %s from %s (sizes: %s)", ico_path, src_path, ", ".join(str(w) for w, _ in ICON_SIZES)
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Build the PageVault .ico from static/icon.png.")
    parser.add_argument("--src", type=Path, default=DEFAULT_SRC, help="Master PNG path.")
    parser.add_argument("--ico", type=Path, default=DEFAULT_ICO, help="Output .ico path.")
    args = parser.parse_args(argv)
    generate(args.src, args.ico)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
